export const usersData = [
    {
        id: "USR-1001",
        username: "admin.helpdesk",
        fullName: "Admin",
        email: "admin@helpdesk.com",
        password: "looklook",
        role: "admin",
        avatar: "https://i.pravatar.cc/300?img=47",
    },
    {
        id: "USR-1002",
        username: "david.mensah",
        fullName: "David Mensah",
        email: "david.mensah@example.com",
        password: "David#2026Help",
        role: "agent",
        avatar: "https://i.pravatar.cc/300?img=12",
    },
    {
        id: "USR-1003",
        username: "chiamaka.eze",
        fullName: "Chiamaka Eze",
        email: "chiamaka.eze@example.com",
        password: "Chia#2026Help",
        role: "agent",
        avatar: "https://i.pravatar.cc/300?img=32",
    },
    {
        id: "USR-1004",
        username: "kwame.boateng",
        fullName: "Kwame Boateng",
        email: "kwame.boateng@example.com",
        password: "Kwame#2026Help",
        role: "agent",
        avatar: "https://i.pravatar.cc/300?img=68",
    },
    {
        id: "USR-1005",
        username: "lina.hassan",
        fullName: "Lina Hassan",
        email: "lina.hassan@example.com",
        password: "Lina#2026Help",
        role: "viewer",
        avatar: "https://i.pravatar.cc/300?img=5",
    },
    {
        id: "USR-1006",
        username: "samuel.adeyemi",
        fullName: "Samuel Adeyemi",
        email: "samuel.adeyemi@example.com",
        password: "Sam#2026Help",
        role: "viewer",
        avatar: "https://i.pravatar.cc/300?img=15",
    },
];