export const usersData = [
    {
        id: "USR-1001",
        username: "admin.helpdesk",
        fullName: "Admin",
        email: "admin@helpdesk.com",
        password: "looklook",
        role: "admin",
        avatar: "https://api.dicebear.com/9.x/avataaars/png?seed=Admin&backgroundColor=transparent&size=512",
    },
    {
        id: "USR-1002",
        username: "david.mensah",
        fullName: "David Mensah",
        email: "david.mensah@yahoo.com",
        password: "looklook1",
        role: "user",
        avatar: "https://api.dicebear.com/9.x/avataaars/png?seed=David%20Mensah&backgroundColor=transparent&size=512",
    },
    {
        id: "USR-1003",
        username: "chiamaka.eze",
        fullName: "Chiamaka Eze",
        email: "chiamaka.eze@hotmail.com",
        password: "123456789",
        role: "user",
        avatar: "https://api.dicebear.com/9.x/avataaars/png?seed=Chiamaka%20Eze&backgroundColor=transparent&size=512",
    },
    {
        id: "USR-1004",
        username: "kwame.boateng",
        fullName: "Kwame Boateng",
        email: "kwame.boateng@example.com",
        password: "Kwame#2026Help",
        role: "user",
        avatar: "https://api.dicebear.com/9.x/avataaars/png?seed=Kwame%20Boateng&backgroundColor=transparent&size=512",
    },
    {
        id: "USR-1005",
        username: "lina.hassan",
        fullName: "Lina Hassan",
        email: "lina.hassan@example.com",
        password: "Lina#2026Help",
        role: "user",
        avatar: "https://api.dicebear.com/9.x/avataaars/png?seed=Lina%20Hassan&backgroundColor=transparent&size=512",
    },
    {
        id: "USR-1006",
        username: "samuel.adeyemi",
        fullName: "Samuel Adeyemi",
        email: "samuel.adeyemi@example.com",
        password: "Sam#2026Help",
        role: "user",
        avatar: "https://api.dicebear.com/9.x/avataaars/png?seed=Samuel%20Adeyemi&backgroundColor=transparent&size=512",
    },
    {
        id: "USR-1007",
        username: "grace.okonkwo",
        fullName: "Grace Okonkwo",
        email: "grace.okonkwo@example.com",
        password: "Grace#2026Help",
        role: "user",
        avatar: "https://api.dicebear.com/9.x/avataaars/png?seed=Grace%20Okonkwo&backgroundColor=transparent&size=512",
    },
    {
        id: "USR-1008",
        username: "john.smith",
        fullName: "John Smith",
        email: "john.smith@example.com",
        password: "John#2026Help",
        role: "user",
        avatar: "https://api.dicebear.com/9.x/avataaars/png?seed=John%20Smith&backgroundColor=transparent&size=512",
    },
    {
        id: "USR-1009",
        username: "amara.williams",
        fullName: "Amara Williams",
        email: "amara.williams@example.com",
        password: "Amara#2026Help",
        role: "user",
        avatar: "https://api.dicebear.com/9.x/avataaars/png?seed=Amara%20Williams&backgroundColor=transparent&size=512",
    },
    {
        id: "USR-1010",
        username: "michael.johnson",
        fullName: "Michael Johnson",
        email: "michael.johnson@example.com",
        password: "Michael#2026Help",
        role: "user",
        avatar: "https://api.dicebear.com/9.x/avataaars/png?seed=Michael%20Johnson&backgroundColor=transparent&size=512",
    },
    {
        id: "USR-1011",
        username: "sophia.brown",
        fullName: "Sophia Brown",
        email: "sophia.brown@example.com",
        password: "Sophia#2026Help",
        role: "user",
        avatar: "https://api.dicebear.com/9.x/avataaars/png?seed=Sophia%20Brown&backgroundColor=transparent&size=512",
    },
    {
        id: "USR-1012",
        username: "ethan.davis",
        fullName: "Ethan Davis",
        email: "ethan.davis@example.com",
        password: "Ethan#2026Help",
        role: "user",
        avatar: "https://api.dicebear.com/9.x/avataaars/png?seed=Ethan%20Davis&backgroundColor=transparent&size=512",
    },
    {
        id: "USR-1013",
        username: "isabella.martinez",
        fullName: "Isabella Martinez",
        email: "isabella.martinez@example.com",
        password: "Isabella#2026Help",
        role: "user",
        avatar: "https://api.dicebear.com/9.x/avataaars/png?seed=Isabella%20Martinez&backgroundColor=transparent&size=512",
    },
    {
        id: "USR-1014",
        username: "daniel.garcia",
        fullName: "Daniel Garcia",
        email: "daniel.garcia@example.com",
        password: "Daniel#2026Help",
        role: "user",
        avatar: "https://api.dicebear.com/9.x/avataaars/png?seed=Daniel%20Garcia&backgroundColor=transparent&size=512",
    },
    {
        id: "USR-1015",
        username: "natasha.patel",
        fullName: "Natasha Patel",
        email: "natasha.patel@example.com",
        password: "Natasha#2026Help",
        role: "user",
        avatar: "https://api.dicebear.com/9.x/avataaars/png?seed=Natasha%20Patel&backgroundColor=transparent&size=512",
    },
];